-- +goose Up
INSERT INTO product (name, description, price, quantity, image_url) VALUES
('iPhone 14 Pro', 'The latest flagship smartphone from Apple.', 99900, 50, NULL),
('Samsung Galaxy S22 Ultra', 'Top-of-the-line smartphone with cutting-edge features.', 109900, 40, NULL),
('Sony PlayStation 5', 'Next-generation gaming console with stunning graphics and performance.', 49900, 30, NULL),
('Xbox Series X', 'Powerful gaming console for immersive gaming experiences.', 49900, 35, NULL),
('Canon EOS R5', 'Professional-grade mirrorless camera with outstanding image quality.', 389900, 20, NULL),
('Nikon Z9', 'High-performance flagship camera for professional photographers.', 549900, 15, NULL),
('LG OLED C1 65" TV', 'Immersive OLED TV with stunning picture quality.', 229900, 10, NULL),
('Dell XPS 15 Laptop', 'Powerful laptop with high-resolution display and premium build quality.', 179900, 25, NULL),
('Amazon Echo Dot', 'Smart speaker with Alexa voice control for hands-free convenience.', 4999, 60, NULL),
('Nintendo Switch', 'Versatile gaming console for gaming at home or on the go.', 29900, 55, NULL),
('Nike Air Max 270', 'Iconic Nike sneakers with Air Max cushioning for comfort.', 79900, 20, NULL),
('Instant Pot Duo 6-Quart', 'Multi-functional pressure cooker for easy and quick cooking.', 7999, 30, NULL),
('Samsung 55" 4K Smart TV', 'High-resolution smart TV with immersive viewing experience.', 69900, 15, NULL),
('Apple AirPods Pro', 'Wireless earbuds with active noise cancellation for immersive sound.', 19900, 40, NULL),
('KitchenAid Stand Mixer', 'Powerful stand mixer for effortless baking and cooking.', 34900, 20, NULL),
('Adidas Ultraboost Running Shoes', 'High-performance running shoes with responsive cushioning.', 99900, 25, NULL),
('Cuisinart 14-Cup Food Processor', 'Versatile food processor for easy meal preparation.', 15900, 20, NULL),
('Fujifilm Instax Mini 11', 'Compact instant camera for capturing memories on-the-go.', 6999, 35, NULL),
('Le Creuset Dutch Oven', 'Premium enameled cast iron Dutch oven for cooking delicious meals.', 349900, 10, NULL),
('Vitamix Blender', 'High-performance blender for smoothies, soups, and more.', 39900, 15, NULL),
('Bose QuietComfort 35 II Headphones', 'Noise-cancelling headphones for immersive audio experience.', 29900, 25, NULL),
('Lego Millennium Falcon', 'Iconic Star Wars Lego set for fans and collectors.', 79900, 10, NULL),
('Crock-Pot Slow Cooker', 'Convenient slow cooker for delicious, fuss-free meals.', 2999, 30, NULL),
('Fitbit Versa 3', 'Advanced fitness tracker with built-in GPS and heart rate monitoring.', 22900, 35, NULL),
('Roku Streaming Stick+', 'Compact streaming device for high-definition entertainment.', 4999, 40, NULL),
('Hamilton Beach Coffee Maker', 'Programmable coffee maker for brewing fresh coffee.', 4999, 30, NULL),
('Coleman Sundome Tent', 'Spacious camping tent for outdoor adventures.', 4999, 20, NULL),
('Razer DeathAdder Elite Gaming Mouse', 'High-precision gaming mouse for competitive gaming.', 5999, 30, NULL),
('NutriBullet Blender Combo', 'Versatile blender for making smoothies, soups, and more.', 13900, 25, NULL),
('JBL Flip 5 Portable Bluetooth Speaker', 'Portable speaker with powerful sound for on-the-go entertainment.', 8999, 40, NULL),
('Puma RS-X Sneakers', 'Stylish sneakers with retro-inspired design.', 6999, 25, NULL),
('Black+Decker 20V MAX Drill', 'Comprehensive tool kit for DIY projects and home repairs.', 6999, 20, NULL),
('Sony WH-1000XM4 Headphones', 'Premium headphones with industry-leading noise cancellation technology.', 34900, 30, NULL),
('Ring Video Doorbell', 'Smart doorbell with HD video and two-way talk.', 9999, 35, NULL),
('L.L.Bean Bean Boots', 'Iconic outdoor boots for all-weather adventures.', 12900, 25, NULL),
('Google Nest Thermostat', 'Smart thermostat for energy-saving home temperature control.', 12900, 30, NULL),
('Cuisinart Griddler', 'Versatile countertop grill for indoor grilling and cooking.', 9999, 25, NULL),
('Play-Doh Fun Tub', 'Creative playset for molding and shaping with Play-Doh.', 1499, 40, NULL),
('Gaiam Yoga Mat', 'Non-slip yoga mat for comfortable and stable yoga practice.', 2499, 45, NULL),
('Anker PowerCore Portable Charger', 'High-capacity portable charger for charging devices on-the-go.', 2999, 50, NULL),
('Dyson V11 Cordless Vacuum Cleaner', 'Powerful cordless vacuum cleaner with advanced filtration.', 59900, 15, NULL),
('Calphalon Nonstick Cookware Set', 'Premium nonstick cookware set for versatile cooking.', 24900, 20, NULL),
('Jabra Elite 75t True Wireless Earbuds', 'Wireless earbuds with customizable sound and secure fit.', 17999, 30, NULL),
('Coleman Portable Camping Chair', 'Foldable camping chair for outdoor relaxation.', 1999, 35, NULL),
('Apple MacBook Air M2', 'Ultra-thin laptop with Apple M2 chip for powerful everyday performance.', 119900, 30, NULL),
('Logitech MX Master 3S Mouse', 'Ergonomic wireless mouse with precision scrolling for productivity.', 9999, 40, NULL),
('Sony A7 IV Mirrorless Camera', 'Full-frame mirrorless camera for versatile photo and video.', 249900, 12, NULL),
('Bose SoundLink Revolve+ II', 'Portable Bluetooth speaker with 360-degree sound.', 32900, 20, NULL),
('Apple Watch Series 8', 'Advanced smartwatch with health monitoring and fitness tracking.', 39900, 45, NULL),
('Samsung Galaxy Buds2 Pro', 'Premium wireless earbuds with intelligent active noise cancellation.', 22900, 35, NULL),
('Dyson Airwrap Styler', 'Multi-functional hair styler powered by the Dyson digital motor.', 59900, 18, NULL),
('GoPro HERO11 Black', 'Waterproof action camera with 5.3K video and HyperSmooth stabilization.', 39900, 25, NULL),
('Sonos One SL Speaker', 'Compact smart speaker with rich, room-filling sound.', 19900, 30, NULL),
('Kindle Paperwhite', 'Waterproof e-reader with a flush-front design and adjustable warm light.', 13900, 50, NULL),
('Breville Barista Express', 'Semi-automatic espresso machine with built-in grinder.', 69900, 10, NULL),
('Philips Sonicare DiamondClean', 'Electric toothbrush with smart sensor technology.', 19900, 40, NULL),
('Theragun Elite Massage Gun', 'Percussive therapy device for deep muscle treatment and recovery.', 39900, 15, NULL),
('Oculus Quest 2 VR Headset', 'All-in-one virtual reality headset for immersive gaming.', 29900, 20, NULL),
('Herman Miller Aeron Chair', 'Ergonomic office chair designed for long hours of comfortable sitting.', 139900, 8, NULL),
('Roomba j7+ Robot Vacuum', 'Smart robot vacuum with obstacle avoidance and self-emptying base.', 79900, 15, NULL),
('Keychron Q1 Mechanical Keyboard', 'Customizable mechanical keyboard with hot-swappable switches.', 16900, 25, NULL),
('Marshall Stanmore II Speaker', 'Iconic Bluetooth speaker with powerful, room-filling Marshall sound.', 34900, 18, NULL),
('Yeti Rambler 36oz Bottle', 'Double-wall vacuum insulated water bottle for all-day temperature retention.', 4499, 60, NULL),
('DJI Mini 3 Pro Drone', 'Lightweight foldable drone with 4K HDR video and obstacle sensing.', 75900, 12, NULL),
('Nespresso Vertuo Next', 'Single-serve coffee and espresso machine with centrifusion technology.', 17900, 30, NULL),
('Apple iPad Air', 'Versatile tablet with M1 chip for creative and productivity workflows.', 59900, 35, NULL),
('Samsung Galaxy Tab S8', 'Premium Android tablet with S Pen and 120Hz display.', 69900, 20, NULL),
('Cricut Maker 3', 'Smart cutting machine for DIY crafts, cards, and custom projects.', 39900, 15, NULL),
('Weber Spirit II E-310 Gas Grill', 'Three-burner gas grill with porcelain-enameled cast-iron grates.', 49900, 10, NULL),
('Hydro Flask 32oz Wide Mouth', 'Stainless steel insulated water bottle that keeps drinks cold for 24 hours.', 4499, 55, NULL),
('Osprey Atmos AG 65 Backpack', 'Anti-gravity suspension hiking backpack for multi-day adventures.', 27000, 15, NULL),
('Patagonia Nano Puff Jacket', 'Lightweight and windproof insulated jacket for outdoor activities.', 19900, 30, NULL),
('Hoka Bondi 8 Running Shoes', 'Ultra-cushioned running shoes for maximum comfort on long runs.', 16500, 35, NULL),
('Stanley Quencher H2.0 Tumbler', 'Double-wall vacuum insulated tumbler with FlowState lid.', 3500, 80, NULL),
('Ember Temperature Control Mug', 'Smart coffee mug that maintains your ideal drinking temperature.', 12900, 25, NULL),
('Ooni Koda 16 Pizza Oven', 'Gas-powered outdoor pizza oven that reaches 950F in 20 minutes.', 59900, 10, NULL),
('Lululemon Align Leggings', 'Buttery soft leggings designed for yoga and everyday wear.', 9800, 45, NULL),
('Under Armour HOVR Phantom 3', 'Connected running shoes with real-time form coaching.', 16000, 20, NULL),
('Garmin Fenix 7 GPS Watch', 'Multi-sport GPS smartwatch with advanced training features.', 69900, 15, NULL),
('Peak Design Everyday Backpack', 'Versatile camera and laptop backpack with customizable dividers.', 28900, 18, NULL),
('Sennheiser Momentum 4 Headphones', 'Premium wireless headphones with adaptive noise cancellation.', 34900, 22, NULL),
('LG 34" UltraWide Monitor', 'Curved ultrawide monitor for immersive productivity and gaming.', 44900, 12, NULL),
('Secretlab Titan Evo Gaming Chair', 'Ergonomic gaming chair with 4-way lumbar support system.', 44900, 15, NULL),
('Samsung 980 PRO 2TB SSD', 'High-speed NVMe solid state drive for gaming and creative workloads.', 17999, 40, NULL),
('Razer BlackWidow V4 Keyboard', 'Mechanical gaming keyboard with Razer Green switches and RGB lighting.', 16999, 25, NULL),
('ASUS ROG Swift 27" Gaming Monitor', '1440p gaming monitor with 165Hz refresh rate and G-Sync.', 62900, 10, NULL),
('Sony 65" Bravia XR A80K OLED TV', 'Cognitive processor XR powered OLED TV with Dolby Vision and Atmos.', 179900, 8, NULL),
('Ninja Foodi 9-in-1 Pressure Cooker', 'Multi-cooker that pressure cooks, air fries, and slow cooks.', 14900, 25, NULL),
('All-Clad D3 Stainless Steel Fry Pan', 'Tri-ply stainless steel fry pan for even heat distribution.', 12999, 20, NULL),
('Bosch 800 Series Dishwasher', 'Ultra-quiet dishwasher with CrystalDry technology for perfect drying.', 109900, 5, NULL),
('iRobot Braava Jet m6 Robot Mop', 'Smart robot mop with precision jet spray and systematic cleaning.', 44900, 12, NULL),
('Tile Pro Bluetooth Tracker', 'Long-range Bluetooth tracker to find your keys, wallet, and more.', 3499, 70, NULL),
('Nanoleaf Shapes Hexagon Light Panels', 'Modular smart LED light panels with touch and music sync.', 19999, 18, NULL),
('Sony WF-1000XM5 Earbuds', 'Compact true wireless earbuds with best-in-class noise cancellation.', 29900, 30, NULL),
('Logitech StreamCam Webcam', '1080p 60fps webcam with auto-framing for streaming and video calls.', 16999, 22, NULL),
('CalDigit TS4 Thunderbolt 4 Dock', 'Premium docking station with 18 ports for laptops and desktops.', 39900, 10, NULL),
('Bellroy Tech Kit Compact', 'Organized pouch for cables, chargers, and small tech accessories.', 5900, 40, NULL),
('Aeropress Original Coffee Maker', 'Portable coffee press that brews smooth espresso-style coffee in minutes.', 3499, 50, NULL),
('New Balance 990v5 Sneakers', 'Heritage running shoes handcrafted in the USA with premium materials.', 18499, 20, NULL),
('Elgato Stream Deck MK.2', 'Customizable LCD key controller for streamers and content creators.', 14999, 28, NULL);

-- +goose Down
DELETE FROM product;
